Scale the rofi window on HiDPI. Better DPI detection.
ubuntu-mate/mate-hud pull request #61
Opened 2022-04-09 03:31 UTC by twa022

#59

2022-04-09 03:48 UTC, twa022 commented
I don't have a hidpi monitor to test, but it worked okay when I forced the scale on mine.

Would it be better to make copies of the themes for hidpi and override the theme rather than just overriding the width so all the theme properties expressed in px can be doubled?

2022-04-09 18:04 UTC, twa022 commented
I like #62 better as a solution

2022-04-11 10:46 UTC, flexiondotorg requested changes
Can you rework this to not require pyxr? Perhaps this is available via GDK?

2022-04-11 10:46 UTC, flexiondotorg commented on usr/lib/mate-hud/mate-hud
> +    res_prop = display.Display().screen().root.get_full_property(Xatom.RESOURCE_MANAGER, Xatom.STRING)
Sadly `pyxr` is not packaged for Debian/Ubuntu or Fedora/RHEL

2022-04-12 02:27 UTC, closed without merging