Another scaling take for HiDPI (I like this one best)
ubuntu-mate/mate-hud pull request #62
Opened 2022-04-09 18:03 UTC by twa022

#59 I think this better than what I posted on #61

2022-04-11 10:46 UTC, flexiondotorg requested changes
Can you rework this to not require pyxr? Perhaps this is available via GDK?

2022-04-11 10:46 UTC, flexiondotorg commented on usr/lib/mate-hud/mate-hud
> +    res_prop = display.Display().screen().root.get_full_property(Xatom.RESOURCE_MANAGER, Xatom.STRING)
Sadly `pyxr` is not packaged for Debian/Ubuntu or Fedora/RHEL

2022-04-12 02:27 UTC, twa022 commented
Updated to get DPI through GDK (poorly named function, but that's a lot easier...)

2022-04-12 14:33 UTC, flexiondotorg approved these changes
LGTM :+1:

2022-04-12 14:33 UTC, merged